## swagger
knife4j:
  enable: true
  title: Onex-Shop-API
  description: Onex商城接口
  setting:
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Copyright  2021-[nb6868](https://www.nb6868.com/)

## onex
onex:
  # 登录配置
  auth:
    ## 权限控制扫描包
    access-scan-package: com.nb6868.onex.shop.modules
    configs:
      ## 商城-小程序
      SHOP_WXMA_PHONE:
        type: SHOP_WXMA_PHONE
        token-policy: jwt
        token-key: e9HCUI@cYR
        verify-type: jwt
        ## 不做权限和角色控制
        permission-base: true
        role-base: false
  # 存储配置
  oss:
    configs:
      OSS_PUBLIC:
        type: aliyun
        domain: https://xxx.oss-cn-hangzhou.aliyuncs.com/
        prefix: xxx
        endPoint: http://oss-cn-hangzhou.aliyuncs.com/
        accessKeyId: xxx
        accessKeySecret: xxx
        bucketName: xxx
        keepFileName: false
  # 微信配置
  wechat:
    ## 小程序配置
    ma:
      # 配置
      configs:
        # 小程序配置
        WX_MA:
          type: MA
          appid: xxx
          secret: xxx
