server:
  port: 8083
  servlet:
    context-path: /xcoder

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/onex?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: onex
    password: onex
    #oracle配置
#    driverClassName: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@47.100.206.162:1521:xe
#    username: onex
#    password: 123456
    #SQLServer配置
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=security_enterprise
#    username: sa
#    password: 123456
    #PostgreSQL配置
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://192.168.10.10:5432/security_enterprise
#    username: postgres
#    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/


mybatis:
  mapperLocations: classpath:mapper/**/*.xml


pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql】
database: mysql
